### ISSUE TITLE
After Download Cannot run mvn -DskipTests package

### ISSUE THREAD

**Issue by MMalani** [qubole/streamx#26] opened 2016-12-13 15:50 UTC
Get:  Failure to find io.confluent:kafka-connect-avro-converter:jar:3.0.0 - Cannot seem to find the Maven repository with for this version. can someone help?

**Comment by PraveenSeluka** [comment] 2016-12-13 23:52
@MMalani I just did a clean and package after cleaning up local .m2 repo. It was able to download it  http://packages.confluent.io/maven/io/confluent/kafka-connect-avro-converter/3.0.0/kafka-connect-avro-converter-3.0.0.pom

Do you any issues accessing Confluent maven repository ?

Thanks

**Comment by MMalani** [comment] 2016-12-14 10:14
Thanks .. I did a clean and then package that did not work - but did not clean my .m2 repo -- I will try that next - 
I am able too click on the above link and see the pom

fyi this is the error I see Could not resolve dependencies for project com.qubole:streamx:jar:0.1.0-SNAPSHOT: Could not find artifact io.confluent:kafka-connect-avro-converter:jar:3.0.0 in internal-repository (http://nexus.sb.karmalab.net/nexus/content/groups/public/)

**Comment by jocelyndrean** [comment] 2016-12-14 16:52
@MMalani I tried on a fresh new server but didn't get your error.
```
[hadoop@ip-10-91-26-11 ~]$ curl -sSLO  http://www-eu.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
[hadoop@ip-10-91-26-11 ~]$ tar xzvf apache-maven-3.3.9-bin.tar.gz
[hadoop@ip-10-91-26-11 ~]$ export PATH=/home/hadoop/apache-maven-3.3.9/bin:$PATH
[hadoop@ip-10-91-26-11 ~]$ git clone https://github.com/qubole/streamx.git
[hadoop@ip-10-91-26-11 ~]$ cd streamx
[hadoop@ip-10-91-26-11 streamx]$ mvn -DskipTests package
```

**Comment by PraveenSeluka** [comment] 2016-12-14 19:27
@MMalani am not a Maven expert - it looks like its looking in your internal repo rather than confluent repo. Mostly, this is hinting at some issues in connecting to confluent repo from the machine you are running. (Or is there some sort of restriction in Maven to access internal repos only?)

**Comment by PraveenSeluka** [comment] 2016-12-19 19:42
@MMalani Am closing this issue as we could not reproduce this in new machine too. (and this looks specific to your environment). Please reopen if you see anything StreamX specific.

**Closed as completed by PraveenSeluka** 2016-12-19 19:42 UTC

**Comment by MMalani** [comment] 2016-12-21 17:32
Sorry for not getting back sooner .. Thank you for all your help . It could be my env. I got it working but I had to change the confluent version to :  
<confluent.version>3.0.0-hcom-1-SNAPSHOT</confluent.version>

I will try cleaning up my local .m2 to see if it can help
